```{r options, echo=FALSE}
suppressMessages(library(pellys))
options(width = 98)
```
# Pelly's Players Stats (2011-2013)


## Cumulative Stats

```{r setup, echo=FALSE}
data301<-readPellysData("301")
stats301_noNA<-na.omit(data301[data301$Name!="Forfeit",])
stats301_noNA[,2]<-as.Date(stats301_noNA[,2], "%m/%d/%Y")
statsCricket<-readPellysData("cricket")
statsCricket_noNA<-na.omit(statsCricket)
statsCricket_noNA[,2]<-as.Date(statsCricket_noNA[,2], "%m/%d/%Y")
cricketTeams<-paste(statsCricket_noNA$Name1,statsCricket_noNA$Name2,sep=" ")
cricketTeams<-gsub("  "," ",cricketTeams)
cricketTeamsNum<-as.numeric(unlist(lapply(cricketTeams,function(x) sum(strtoi(charToRaw(x),base=16)))))
cricketTeamsName<-cricketTeams[order(cricketTeamsNum)][!duplicated(cricketTeamsNum[order(cricketTeamsNum)])]
cricketTeams<-data.frame(cricketTeamsName,cricketTeamsNum=cricketTeamsNum[order(cricketTeamsNum)][!duplicated(cricketTeamsNum[order(cricketTeamsNum)])])
statsCricket_noNA<-data.frame(statsCricket_noNA,cricketTeamsNum)
statsCricket_noNA<-merge(statsCricket_noNA,cricketTeams,by="cricketTeamsNum",all.x=T)
byPairCricket<-by(statsCricket_noNA,statsCricket_noNA$cricketTeamsName,winPercCricket)
byPerson301<-by(stats301_noNA,stats301_noNA$Name,winPerc301)
byPerson301Avg<-by(stats301_noNA,stats301_noNA$Name,stats301)
byPairCricket<-do.call("rbind",byPairCricket)
byPerson301<-do.call("rbind",byPerson301)
byPerson301Avg<-do.call("rbind",byPerson301Avg)


#Player Index
jeffInd<-as.character(statsCricket_noNA$Name1)=="Jeff"|as.character(statsCricket_noNA$Name2)=="Jeff"
rolandInd<-as.character(statsCricket_noNA$Name1)=="Roland"|as.character(statsCricket_noNA$Name2)=="Roland"
mikeInd<-as.character(statsCricket_noNA$Name1)=="Mike"|as.character(statsCricket_noNA$Name2)=="Mike"
kennyInd<-as.character(statsCricket_noNA$Name1)=="Kenny"|as.character(statsCricket_noNA$Name2)=="Kenny"
edInd<-as.character(statsCricket_noNA$Name1)=="Ed"|as.character(statsCricket_noNA$Name2)=="Ed"
CharlesInd<-as.character(statsCricket_noNA$Name1)=="Charles"|as.character(statsCricket_noNA$Name2)=="Charles"
jeffCricket<-winPercCricket(statsCricket_noNA[jeffInd,])
rolandCricket<-winPercCricket(statsCricket_noNA[rolandInd,])
mikeCricket<-winPercCricket(statsCricket_noNA[mikeInd,])
kennyCricket<-winPercCricket(statsCricket_noNA[kennyInd,])
edCricket<-winPercCricket(statsCricket_noNA[edInd,])
CharlesCricket<-winPercCricket(statsCricket_noNA[CharlesInd,])
playerCricket<-rbind(jeffCricket,rolandCricket,mikeCricket,kennyCricket,edCricket,CharlesCricket)
row.names(playerCricket)<-c("Jeff","Roland","Mike","Kenny","Ed","Charles")
playerCricket<-playerCricket[order(playerCricket$percent,decreasing=T),]


teamCricket<-winPercCricket(statsCricket_noNA)
row.names(teamCricket)<-"Team"
playerCricket<-rbind(playerCricket,teamCricket)
team301<-winPerc301(stats301_noNA)
team301Avg<-stats301(stats301_noNA)
byPairCricket<-by(statsCricket_noNA,statsCricket_noNA$cricketTeamsName,winPercCricket)
byPerson301<-by(stats301_noNA,stats301_noNA$Name,winPerc301)
byPerson301Avg<-by(stats301_noNA,stats301_noNA$Name,stats301)
byPairCricket<-do.call("rbind",byPairCricket)
byPerson301<-do.call("rbind",byPerson301)
byPerson301Avg<-do.call("rbind",byPerson301Avg)
byPairCricket<-byPairCricket[order(byPairCricket$percent,decreasing=T),]
byPerson301<-byPerson301[order(byPerson301$percent,decreasing=T),]
row.names(team301)<-"Team"
byPerson301<-rbind(byPerson301,team301)
byPerson301Avg<-byPerson301Avg[order(byPerson301Avg$avgPPD,decreasing=T),]
row.names(team301Avg)<-"Team"
byPerson301Avg<-rbind(byPerson301Avg,team301Avg)
```

### Cricket Wins By Player
```{r results='asis', echo=FALSE}
kable(playerCricket,"html")
```

### 301 Wins By Player
```{r results='asis', echo=FALSE}
kable(byPerson301,"html")
```

### 301 Stats By Player
```{r results='asis', echo=FALSE}
kable(byPerson301Avg,"html")
```

### Cricket by Pair
```{r results='asis', echo=FALSE}
kable(byPairCricket,"html")
```
